1st commit
VenKaas/final-project-10th-sprint pull request #1
Opened 2024-03-19 15:06 UTC by VenKaas

2024-03-19 16:04 UTC, dirtymew requested changes
Привет Владислав 

Хорошая работа - тема сложная и выполнил почти все верно.

Дал комментарии что нужно исправить

2024-03-19 16:04 UTC, dirtymew commented on precode.sh
> +cp -r -T ./dir2 ./dir3/dir4
-T у меня например ошибку выдает cp: illegal option -- T

2024-03-19 16:04 UTC, dirtymew commented on precode.sh
> +NAME="всем студентам"
тут требуется создать не обычную переменную а переменную окружения

2024-03-19 16:04 UTC, dirtymew commented on precode.sh
> +rm -r -f task
-f тут  не нужен

2024-03-20 09:26 UTC, merged

2024-03-20 09:36 UTC, VenKaas commented
Замерджил зачем-то

2024-03-20 09:52 UTC, dirtymew commented
> Замерджил зачем-то

это зря - до конца ревью не стоит

2024-03-20 09:55 UTC, dirtymew reviewed
Владислав все отлично теперь вопросов нет

Зачет